baseURL = "/"
languageCode = 'ar'
defaultContentLanguage = "ar"
title = 'KodeMed'
theme = 'PaperMod'


[params]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  rtl = true
  ShowCodeCopyButtons = true
  [params.homeInfoParams]
    Title = "ğŸ‘‹ ÙˆØ§Ø´ Ø§Ø´Ø¨Ø§Ø¨"
    Content = """
      Ø£Ù†Ø§ Ù…Ù‡Ù†Ø¯Ø³ Ø¨Ø±Ù…Ø¬ÙŠØ§Øª Ù…Ù‡ØªÙ… Ø¨Ø§Ù„Ù€ System DesignØŒ 
      ØªØ·ÙˆÙŠØ± Ø§Ù„ØªØ·Ø¨ÙŠÙ‚Ø§Øª Ø¨Ø§Ù„Ù€ Java/SpringØŒ ÙˆØ§Ù„Ù€ Software Architecture.
      Ù‡Ø§Ø¯ Ø§Ù„Ù…Ø¯ÙˆÙ†Ø© Ø¬Ø§ÙŠØ© Ø¨Ø§Ø´ Ù†Ø´Ø§Ø±Ùƒ Ù…Ø¹Ø§ÙƒÙ… Ø§Ù„Ù…Ø¹Ø±ÙØ© Ø¯ÙŠØ§Ù„ÙŠØŒ
      Ù†Ø³Ù‡Ù„ Ø§Ù„ÙÙ‡Ù… Ø¯ÙŠØ§Ù„ Ù…ÙØ§Ù‡ÙŠÙ… Ù…Ø¹Ù‚Ø¯Ø©ØŒ
      ÙˆÙ†Ø³Ø§Ù‡Ù… ÙÙ€ Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø§Ù„ØªÙ‚Ù†ÙŠ  Ø¨Ø§Ù„Ø¯Ù‘Ø§Ø±Ø¬Ø© Ø§Ù„Ù…ØºØ±Ø¨ÙŠØ©.

      ØºØ§Ø¯ÙŠ ØªÙ„Ù‚Ø§Ùˆ Ù‡Ù†Ø§ Ù…ÙˆØ§Ø¶ÙŠØ¹ Ù…ÙÙŠØ¯Ø© Ø¹Ù„Ù‰:
      - Design Patterns ğŸ§ 
      - Spring Boot Ùˆ Java â˜•
      - Microservices Architecture ğŸ§±
      - ÙˆØ£ÙÙƒØ§Ø± ÙÙ€ System Design 

      Ù†ØªÙ…Ù†Ù‰ ØªØ³ØªØ§ÙØ¯ÙˆØŒ ÙˆÙ…Ø±Ø­Ø¨Ø§ Ø¨Ø£ÙŠ Ø§Ù‚ØªØ±Ø§Ø­Ø§Øª â¤ï¸
      """
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/MEDAFKARI"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/medafk"


[[menu.main]]
  name = "Ø¯Ø§Ø±"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Ø¨ÙˆØ³ØªØ§Øª"
  url = "/posts/"
  weight = 2



